In [1]:
import numpy as np
from scipy import stats

In [2]:
# Central tendency  : It Gives us the basic distribution of data around the central value
# It has three sub topics 1. Mean 2. Median 3. Mode

m  = np.random.randint(7,10,20)

print(m)

[7 8 7 7 7 8 7 8 7 8 7 9 7 9 7 8 8 9 9 7]


### Mean

In [3]:
# mean : average of the all observed value

np.mean(m)

7.7

In [1]:
#Calculating the Mean (Page 33):

#Import required libraries:
from statistics import mean

#Data:
X = [5,8,15,18,25]

#Finding mean:
print("Mean = ",mean(X))

Mean =  14.2


### Weighted Mean

In [2]:
#Calculating the Weighted Mean (Page 34):

#Import required libraries:
import  numpy as np

#Data:
X = [5,10,15,20,25]

#Weight:
Y = [1,2,2,1,1]

#Finding weighted mean:
print("Weighted Mean = ",np.average(X,weights=Y))

Weighted Mean =  14.285714285714286


### Geometric Mean

In [3]:
#Import required libraries:
from scipy import stats

#Data:
X = [20,30,40]

#Finding Geometric Mean:
print("Geometric Mean =",stats.gmean(X))

Geometric Mean = 28.844991406148168


### Harmonic Mean

In [ ]:
#Calculating the Harmonic Mean (Page 37):

#Import required libraries:
from statistics import harmonic_mean

#Data:
X = [20,30,15]

#Finding harmonic mean:
print("Harmonic Mean =",harmonic_mean([20,30,15]))

### Median

In [4]:
# Median :Middle value of the data distribution

#Median (Page 39):
#Odd number of observations:

#Import required libraries:
from statistics import median

#Data:
X =[3,4,11,56,93]

#Finding median:
print("Median =",median(X))

7.5

In [ ]:
#Even number of observations:

#Import required libraries:
from statistics import median

#Data:
X = [3,4,11,56,93,100]

#Finding median:
print("Median =",median(X))

### Mode

In [4]:
# mode:Most frequent occurying value in the data

#Import required libraries:
from statistics import mode

#Data:
X = [2,7,18,32,32,45,78]

#We have to use try-except in case there is no mode or more than one modes:
try:
    print("Mode =",mode(X))
except:
    print("Mode not found!")

Mode = 32


In [5]:
#Import required libraries:
from statistics import mode

#Data:
X = [2,7,18,32,46,54]

#We have to use try-except in case there is no mode or more than one modes:
try:
    print("Mode =",mode(X))
except:
    print("Mode not found!")
    
#An error is thrown when there are no mode.

Mode not found!


In [6]:
#Import required libraries:
from statistics import mode

#Data:
X = [2,7,18,18,34,57,57,89]

#We have to use try-except in case there is no mode or more than one modes:
try:
    print("Mode =",mode(X))
except:
    print("Mode not found!")
      
#An error is thrown in there are more than one mode.

Mode not found!


### Population and Sample

In [6]:
# Population : Total observation  

# Sample : Subset of Population which describes the population

population = np.random.randint(10,20,100)
population

array([11, 15, 11, 18, 12, 12, 13, 18, 15, 19, 10, 11, 16, 19, 10, 17, 10,
       14, 13, 11, 10, 12, 19, 18, 15, 17, 17, 11, 18, 11, 16, 19, 17, 13,
       10, 13, 11, 16, 17, 16, 12, 17, 14, 18, 14, 17, 14, 11, 16, 11, 18,
       18, 14, 16, 15, 13, 12, 14, 10, 10, 16, 16, 15, 12, 19, 10, 10, 16,
       19, 14, 12, 12, 11, 13, 12, 10, 16, 10, 11, 18, 10, 19, 15, 15, 11,
       18, 18, 18, 11, 12, 12, 19, 18, 18, 19, 11, 15, 12, 19, 19])

In [7]:
np.mean(population)

14.36

In [8]:
np.median(population)

14.0

In [9]:
stats.mode(population)

ModeResult(mode=array([11]), count=array([14]))

In [10]:
sample = np.random.choice(population,20)

sample

array([11, 13, 13, 16, 18, 12, 17, 12, 11, 11, 18, 14, 11, 16, 16, 10, 11,
       15, 19, 15])

In [11]:
np.mean(sample)

13.95

In [12]:
np.median(sample)

13.5

In [13]:
stats.mode(sample)

ModeResult(mode=array([11]), count=array([5]))

In [14]:
sample_1 = np.random.choice(population,15)
sample_2 = np.random.choice(population,15)
sample_3 = np.random.choice(population,15)
sample_4 = np.random.choice(population,15)

all_samples = [sample_1,sample_2,sample_3,sample_4]
sample_mean = []

for i in all_samples:
    sample_mean.append(np.mean(i))
    
sample_mean

[14.466666666666667, 15.066666666666666, 14.2, 14.066666666666666]

In [15]:
np.mean(sample_mean)

14.45

In [16]:
np.mean(population)

14.36

### Data Spread 

In [17]:
# Measure of Spread : It Gives the measure of variability in the data and how well data is distributed
# To get the overall description of the data we use central tendency and measure of descrition.

# Where do we use it ? : Election pools;Judge test Scopre ; Percentage increase in salary


In [18]:
# Measure of Spread has 4 categories : 1. range 2. Quartile 3. Variance 4. Standard Deviation

### Range

In [19]:
# Range : It gives how well data is spreadout

n = np.random.rand(9)
print(n)

# Range
np.max(n) - np.min(n)

[0.716728   0.29876914 0.83404657 0.45302692 0.76203109 0.21339676
 0.27063829 0.02723492 0.45764429]


0.8068116544730503

### Quartile

In [20]:
# Quartile : Devide the data into 4 sets and get the median in between

# First quartile
Q1 = np.percentile(n,25)
print("Q1 = ",Q1)

# Secnd quartile
Q2 = np.percentile(n,50)
print("Q2 = ",Q2)

# Third quartile
Q3 = np.percentile(n,75)
print("Q3 = ",Q3)

# IQR = Interquartile range

IQR = Q3 - Q1

print("IQR = ",IQR)

Q1 =  0.2706382938531007
Q2 =  0.45302692096593034
Q3 =  0.7167280047885983
IQR =  0.44608971093549765


In [7]:
#Odd number of observations:

#Import required libraries:
import numpy as np
X = [2,3,7,11,29,56,57,78,82,89,95]

#Print the values:
print("Min =",np.quantile(X,0))
print("Q1 =",np.quantile(X,0.25))
print("Q2 =",np.quantile(X,0.50))
print("Q3 =",np.quantile(X,0.75))
print("Max =",np.quantile(X,1))

Min = 2
Q1 = 9.0
Q2 = 56.0
Q3 = 80.0
Max = 95


In [8]:
#Even number of observations:

#Import required libraries:
import numpy as np
X = [2,3,7,11,29,56,57,78,82,89]

#Print the values:
print("Min =",np.quantile(X,0))
print("Q1 =",np.quantile(X,0.25))
print("Q2 =",np.quantile(X,0.50))
print("Q3 =",np.quantile(X,0.75))
print("Max =",np.quantile(X,1))

Min = 2
Q1 = 8.0
Q2 = 42.5
Q3 = 72.75
Max = 89


In [9]:
from scipy import stats

#Data:
X= [1,2,3,4,5,6,7,8,9,10]

#Find the percentile rank:
print("Percentile Rank for 7 =",stats.percentileofscore(X,7,kind="strict"))
print("Percentile Rank for 9 =",stats.percentileofscore(X,9,kind="strict"))

Percentile Rank for 7 = 60.0
Percentile Rank for 9 = 80.0


In [10]:
from scipy import stats

#Data:
X= [1,2,2,3,4,5,5,6,7,8]

#Find the percentile rank:
print("Percentile Rank for 5 =",stats.percentileofscore(X,5,kind="strict"))

Percentile Rank for 5 = 50.0


In [11]:
#Import required libraries:
import numpy as np

#Data:
X = [2,5,6,8,11,45,64,71,77,89,93]

#Print the values:
print("75th =",np.percentile(X,75))
print("70th =",np.percentile(X,70))
print("40th =",np.percentile(X,40))

75th = 74.0
70th = 71.0
40th = 11.0


In [12]:
#Import required libraries:
import numpy as np

#Data:
X = [2,5,6,8,11,45,64,71,77,89,93]

#Print the values:
print("10th =",np.percentile(X,10))
print("25th =",np.percentile(X,25))
print("75th =",np.percentile(X,75))

10th = 5.0
25th = 7.0
75th = 74.0


### Inter Quartile Range(IQR)

In [13]:
#Import required libraries:
from scipy import stats

#Data:
X = [2,5,6,8,11,15,19,21,25,28,31]

#Interquartile Range:
print("Interquartile Range =",stats.iqr(X,interpolation="nearest"))

Interquartile Range = 19


In [14]:
#Import required libraries:
from scipy import stats

#Data:
X = [2,5,6,8,11,15,19,21,25,28,500]

#Range:
print("Range =",(max(X)-min(X)))

#Interquartile Range:
print("Interquartile Range =",stats.iqr(X,interpolation="nearest"))

Range = 498
Interquartile Range = 19


### Variance

In [21]:
# Variance : Tells how spread out(far away) a number is from the mean

In [22]:
population = np.random.randn(100)

population

array([ 0.76606148,  1.01608565,  0.17534481,  0.48779136,  0.23662643,
       -0.59855248,  0.7769444 , -0.23187811, -1.0282223 ,  0.51328009,
       -0.22303071, -0.92391387,  0.43283378,  0.31895869, -0.60346636,
       -0.16546169, -0.01637054, -1.21162588,  1.30349828,  0.65641923,
       -0.6554968 ,  0.36312184, -1.6958296 , -1.25162876,  0.88648833,
        0.3435844 ,  2.31601166,  0.66054709,  0.82585636, -0.29999642,
       -0.37364892,  2.13563883,  0.13294411, -0.68774989, -1.49497689,
       -1.34502917,  0.33581371,  1.57448141,  1.31725475,  1.21558793,
       -1.22918696,  0.36377276,  0.79930769,  0.95654063, -1.21527544,
       -2.56529362, -1.20283752, -0.65913621,  0.74615846, -0.6912409 ,
       -0.43968387, -0.39273598, -1.10586933,  0.962507  ,  0.91655818,
        0.04904157, -0.64053421,  0.07008812,  1.02888626,  1.28605279,
       -0.21196337, -1.77258701, -1.38520936,  2.44936598, -0.15283426,
       -0.21880012,  0.01607557, -1.2604335 ,  0.34273729, -2.26

In [23]:
sample = np.random.choice(population,30)

np.var(sample)

0.744963246236706

In [24]:
np.var(population)

1.1025295922004044

In [15]:
#Import required libraries:
from statistics import variance

#Data:
X = [20,30,25,50,70,45,75]

#Print variance:
print("Variance =",variance(X))

Variance = 466.6666666666667


In [18]:
#Population variance:

#Import required libraries:
from statistics import pvariance

#Data:
X = [20,30,25,50,70,45,75]

#Print variance:
print("Variance =",pvariance(X))

Variance = 400


### Standard Deviation

In [25]:
# Standard Deviation : Square root of variance.while varinace gives you rough idea of spread, 
# the standard deviation iis more concrete, giving you exact distances from the mean

np.std(sample)

0.8631125339355847

In [19]:
#Import required libraries:
from statistics import stdev

#Data:
X = [20,30,25,50,70,45,75]

#Print Standard Deviation:
print("Standard Deviation =",stdev(X))

Standard Deviation = 21.602468994692867


In [20]:
#Population Standard Deviation (Page 68):

#Import required libraries:
from statistics import pstdev

#Data:
X = [20,30,25,50,70,45,75]

#Print Standard Deviation:
print("Standard Deviation =",pstdev(X))

Standard Deviation = 20.0


### Mean Absolute Deviation

In [21]:
#Mean Absolute Deviation (Page 74):

#Import required libraries:
from numpy import mean, absolute

#Data:
X = [18,20,34]

#Print Mean Absolute Deviation:
print("Mean Absolute Deviation = ",mean(absolute(X - mean(X))) )

Mean Absolute Deviation =  6.666666666666667


### Coefficient of variation

In [22]:
#Import required libraries:
from statistics import mean,stdev

#Data:
X = [51710,51350,51400,51450,51460]
Y = [62.009,61.962,62.797,61.996,63.158]

#Standard Deviation:
std_X = stdev(X)
std_Y = stdev(Y)

#Mean:
mean_X = mean(X)
mean_Y = mean(Y)

#Print coefficient of varition:
print("Coefficient of variation for X =",std_X/mean_X)
print("Coefficient of variation for Y =",std_Y/mean_Y)

Coefficient of variation for X = 0.002701021298743379
Coefficient of variation for Y = 0.008920960934171577
